#!/usr/bin/env python3

import argparse
import sys

from go_utils_modules.make_tree import add_arguments as add_make_tree_args
from go_utils_modules.convert import add_arguments as add_convert_args
from go_utils_modules.compare import add_arguments as add_compare_args


def make_parser():
    parser = argparse.ArgumentParser(
        description='GO utilities',
        add_help=False)
    parser.add_argument(
        '-h', '--help', action='help',
        help='Print this help page and exit.')
    subparsers = parser.add_subparsers(title='Subcommands')

    make_tree_subparser = subparsers.add_parser(
        'make_tree', add_help=False,
        help='Make GO tree file.')
    add_make_tree_args(make_tree_subparser)

    convert_subparser = subparsers.add_parser(
        'convert', add_help=False,
        help='Convert an ANNOT file to a per-sequence TSV table.')
    add_convert_args(convert_subparser)

    compare_subparser = subparsers.add_parser(
        'compare', add_help=False,
        help='Perform GO term enrichment analyses.')
    add_compare_args(compare_subparser)

    return parser


if __name__ == '__main__':
    parser = make_parser()
    args = parser.parse_args()
    if args == argparse.Namespace():
        parser.print_help()
        sys.exit(0)
    args.check(args)
    args.main(args)
